### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by keylime-unicorn** [camicarballo/Jukestapose#2]
Server tries playing all songs added to the queue immediately after being added.
Plays the first song fine, but when a second song is added to the queue, the server plays it immediately, on top of the song that's already playing. 
The server is currently using the pyglet music player to play and queue up songs.

**Comment by TBurchfield** [comment]
Was not able to reproduce bug as stated.  I am not getting this issue on the server side, but on the client side.

**Comment by keylime-unicorn** [comment]
Correct. That's also part of the problem: the client is playing songs as well as the server, which is definitely not supposed to happen.

**Comment by TBurchfield** [comment]
Just to clarify _only_ the server is supposed to play the songs, right?

**Comment by keylime-unicorn** [comment]
Yes only the server is supposed to play songs

**Comment by keylime-unicorn** [comment]
Issue closed with PR #6
